### ISSUE TITLE
Peer to Peer Code Review - Team 100 The Aries

### ISSUE THREAD

**Issue by DennisOsido** [kevinfrontend/HTML-CSS-Capstone-Project#1]
Peer Suggestions:
- The standup team advised following the requirements of the capstone. 
- The standup team advised adhering with the typography and colors as required by the project.
- Good Luck on your capstone Kevin!

**Comment by kevcap** [comment]
Thanks @DennisOsido ! Just did the improvments: https://github.com/kevinfrontend/HTML-CSS-Capstone-Project/commit/3a87ef6d09e55869dff5051d392072c10c788cf9
