### ISSUE TITLE
 14 April 2020 - Team 100 - The Aries - Peer to Peer Review 

### ISSUE THREAD

**Issue by Hermela-Fikre** [kevinfrontend/HTML-CSS-Capstone-Project#4]
**Hey @kevinfrontend your work looks way nice! 💥 Congratulations on what you already did, our team really liked that! 😎 👍**

**Positive points:**

    The page looks professional;
    The README is perfect;

**🔧 Your project was approved, so we just have some tips for you:**

    Eliminate the lorem texts so that your page will look like a real page.
    It would be better if you delete the CSS selectors on the HTML files.

With your skills, you'll sure easily walk through it! 👊👊

🙋 Anytime, anything, just reach me by slack, twitter, Instagram;

Keep Healthy 🏊 and Keep Happy 😄!

**Comment by kevcap** [comment]
Thanks for your kind words! And I'll work on that improvements! Grazie
